### ISSUE TITLE
About Gpu Mememory?

### ISSUE THREAD

**Issue by LKmidair** [amundra15/livehand#1]
Hi,dear amundra,live hand is such a great work that I can't wait to try it.
But I am worried about the gpu memory consumed when running the render_pipeline.
So could  you tell me how much gpu memory needed when running this great work?

**Comment by amundra15** [comment]
Hey, I am glad you liked our work.

The method is light on the GPU memory. In our experience, you need ~2.5 GB of memory to run the rendering pipeline.

**Comment by LKmidair** [comment]
Thank you very much！Can't wait to try it !
