### ISSUE TITLE
How to choose annot_subset in data preprocessing

### ISSUE THREAD

**Issue by Eydcao** [amundra15/livehand#10]
Hi dear authors,

Fantastic paper! I am trying to follow up but encountering problems while preparing data from the 2.6M InterHand dataset.

In your `livehand/preprocessing/InterHands2.6M/prepare_dataset.py`, there is:

```python
annot_subset = 'all'  # 'human'
```

This leads to *InterHand2.6M_5fps_batch1/annotations/all/*, i.e., a */all/* subfolder. However, this is inconsistent with the Google Drive you provided, where there are no annot_subset folders. Indeed, using your provided structure without a subfolder, the script reports a file-not-found error.

I tried creating this all folder myself and moving all test/train/valid folders inside, but then received warnings like below:
```sh
WARNING: You are using a MANO model with only 10 shape coefficients.
WARNING: You are using a MANO model with only 10 shape coefficients.
Fix shapedirs bug of MANO
WARNING: You are using a MANO model with only 10 shape coefficients.
WARNING: You are using a MANO model with only 10 shape coefficients.
```

I am unsure if this is expected and am wondering what annot_subset means and how I should set it correctly?

Best,

**Comment by amundra15** [comment]
Hi, I think you have created the folders correctly. The warnings you see are from the MANO class and are expected. 

In case there are still some issues with the pre-processing, you can try using the pre-processed data I have uploaded today.
