### ISSUE TITLE
The command "python prepare_dataset.py" is encountering issues during execution.

### ISSUE THREAD

**Issue by wensite23** [amundra15/livehand#11]
When running python prepare_dataset.py, an error occurs at frame 22402, as shown in the image. How can I resolve this issue?
![8](https://github.com/amundra15/livehand/assets/141139621/3eca0399-a4ea-4447-9ef4-a4b324cc9056)
![9](https://github.com/amundra15/livehand/assets/141139621/09bdc9c8-c51d-4ca2-9d40-cbb99b57a696)

**Comment by amundra15** [comment]
Hi,

Some other people have also reported this issue. Unfortunately, I am not able to replicate it on my system. 

However, I have [uploaded](https://drive.google.com/file/d/1mbROdtclIT0Ifjdjmn_E9F0WdxyP_B4q/view) the pre-processed dataset for one of the identities. You could use that instead.
