### ISSUE TITLE
How do you do LISA-related experiments? It seems that LISA does not publish code.

### ISSUE THREAD

**Issue by MouseChannel** [amundra15/livehand#13]
thanks

**Comment by amundra15** [comment]
Hi,

LISA indeed doesn't provide their code or model. We re-implemented the essential ideas from their paper for the comparison.

**Comment by MouseChannel** [comment]
> Hi,
> 
> LISA indeed doesn't provide their code or model. We re-implemented the essential ideas from their paper for the comparison.

can please share LISA code please.
