### ISSUE TITLE
Preparing datasets fails

### ISSUE THREAD

**Issue by nicolaihaeni** [amundra15/livehand#2]
Hi

Thank you for your great work and for open-sourcing the code. I wanted to test out your approach and ran into the following issue when running livehand/preprocessing/InterHands2.6M/prepare_dataset.py:

 AttributeError: 'MANOExtendet' object has no attribute 'gaussian_proxies.' 
Do you have any insights as to why this happens?

Thank you for your help

**Comment by amundra15** [comment]
Hey, thanks for highlighting the issue. 

I was using an internal pre-processed version of the dataset, so the concerned function was not getting called for me. I have updated mano_util.py to remove dependency on the missing function.

 Let me know if you still face issues.

**Comment by nicolaihaeni** [comment]
That seems to work, thank you
