### ISSUE TITLE
Error in preprocess and What is in data_fol

### ISSUE THREAD

**Issue by agnJason** [amundra15/livehand#3]
In prepare_dataset.py, some error occured:
`
Traceback (most recent call last):
  File "prepare_dataset.py", line 382, in <module>
    mano_mask_gc_lc = largest_component(mano_mask_gc)
  File "prepare_dataset.py", line 232, in largest_component
    max_label, max_size = max([(i, stats[i, cv2.CC_STAT_AREA]) for i in range(1, nb_components)], key=lambda x: x[1])           # Note: range() starts from 1 since 0 is the background label.
ValueError: max() arg is an empty sequence
`

And what should be in the data_fol(/path/to/train/data)?

**Comment by ivashmak** [comment]
I have the same issue with the `largest_component`.

**Comment by amundra15** [comment]
Hi, could you try saving the mask in the variable 'mano_mask_gc'? I suspect that this is empty, and thus the next step is not able to find any connected component here.

As for the data_fol, it is the path where you are saving the pre-processed data.

**Comment by ivashmak** [comment]
Yes, you're right, `mano_mask_gc` returned from `grabcut_refine(mano_mask, rgb)` contains only zeros. I can try to replace  `mano_mask_gc` with `mano_mask` when it happens.

**Comment by amundra15** [comment]
No, that's not a good idea. 

The rendered `mano_mask` does not align very well with the edges of the RGB image because of poor fitting. Thus we use grabcut to refine its edges to match the RGB image. Removing `grabcut_refine()` will resolve the above error but will give you poor segmentation masks.

Your best bet is to step inside this function and see where it is failing. It was working fine when I was running it on the InterHand data, so I am not entirely sure.

**Comment by ivashmak** [comment]
My guess it could be something to do with the OpenCV grabCut, which OpenCV version are you using?

**Comment by amundra15** [comment]
My opencv-python version is `4.8.0.74`.

**Comment by sHaol0w** [comment]
Hi @ivashmak , have you fixed this problem? I encounter the same issue in data preprocessing, and my opencv version is 4.8.0.76

edit: I have tried 4.8.0.74 and it still failed.

**Comment by ivashmak** [comment]
Hi @sHaol0w , updating the OpenCV version helped me a bit, but there were a few more issues that were fixable. First, in some cases cv2.grabCut failed with `mode=cv2.GC_INIT_WITH_MASK`, so I used try-catch, and I ran without this mode whenever it was failing. Second, I think sometimes mask had extra dimension (ie, H x W x 1), so I had to remove the redundant dimension.
