### ISSUE TITLE
About Metashape license

### ISSUE THREAD

**Issue by wyr718** [amundra15/livehand#4]
In the preprocessing stage, I notice that there is a need of Metashape license. Is it a must? since the license is a little bit expensive to get.
<img width="724" alt="截屏2023-10-14 17 48 03" src="https://github.com/amundra15/livehand/assets/84631052/bcc3ddfa-f7d5-451a-96af-9a0cb3cf483a">

**Comment by amundra15** [comment]
Hi,

Thanks for creating the issue. I am not a fan of this dependency either. I used a pre-existing pipeline to set up my codebase, giving rise to this dependency. In reality, metashape is being used just to convert between two different camera coordinate systems. It should be possible to bypass this dependency.

Some other people have also posted issues with the pre-processing pipeline, making me consider uploading the pre-processed data. But this might take some time as I must check the institute's policy around it. In the meantime, your best bet is to get rid of the dependency by modifying the poses_bounds code.

**Comment by wyr718** [comment]
Thanks, I will try

**Comment by amundra15** [comment]
I was able to [upload](https://drive.google.com/file/d/1mbROdtclIT0Ifjdjmn_E9F0WdxyP_B4q/view?usp=sharing) the pre-processed dataset for one of the identities in the paper (test/capture1). In case you are still stuck with this issue, you can consider using this data.

**Comment by ZhaoLizz** [comment]
@wyr718 In fact, you can download Metashape pro and start a 30 days free trial (open Metashape GUI then the free trial dialog would popup). Then install [Metashape python lib ](https://agisoft.freshdesk.com/support/solutions/articles/31000148930-how-to-install-metashape-stand-alone-python-module) and simply `import Metashape`
