### ISSUE TITLE
How to set the dataset folder,confused about the config.txt

### ISSUE THREAD

**Issue by MouseChannel** [amundra15/livehand#7]
in config.txt
    data_fol = path/to/train/data/
    val_data_fol = path/to/val/data/
should data_fol set the  **..../InterHands2.6M/images/val** ,but in https://github.com/amundra15/livehand/blob/7ba95ce657f97924e9a49dc672ab4bd9ea29a0ff/dataset.py#L244
it look likes the parent folder of images
![image](https://github.com/amundra15/livehand/assets/85669016/2684a6a2-e300-4d60-b6f4-0e2891e35512)

and also confused about the 19999.tar contains in the pre_trained model that I download.

**Comment by amundra15** [comment]
The `data_fol` and `val_data_fol` variables expect the path to the pre-processed data. For example, you can use the procedure described [here](https://github.com/amundra15/livehand#preparing-the-dataset) to prepare the dataset, split it into train and val subsets, and provide those paths to the variables above.

And I didn't understand what issue you are facing with the pre_trained model. Could you elaborate?

**Comment by MouseChannel** [comment]
solved
