### ISSUE TITLE
No file named "poses_bounds.npy"

### ISSUE THREAD

**Issue by Nutcracker1320** [amundra15/livehand#8]
function "get_bounds_camera" in "nerf_utils.py", it seems that the variable "all_poses" are all file whose names match(data_fol/*/poses_bounds_fn.npy).
But in the preprocessed data, there is no file named "poses_bounds_fn.npy".

**Comment by amundra15** [comment]
The function actually looks for `args.poses_bounds_fn` whole default value in the config parser is `poses_bounds.npy`. You should be able to find this file in the preprocessed data.
